let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`“${pickRandom(global.bucin)}”`, m)
}
handler.help = ['bucin']
handler.tags = ['quotes']
handler.command = /^(bucin)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

// https://jalantikus.com/tips/kata-kata-bucin/
global.bucin = [
  "Aku memilih untuk sendiri, bukan karena menunggu yang sempurna, tetapi butuh yang tak pernah menyerah.\n *Bye Instagram:* @itz.dapaa",
  "Seorang yang single diciptakan bersama pasangan yang belum ditemukannya.\n *Bye Instagram:* @itz.dapaa",
  "Jomblo. Mungkin itu cara Tuhan untuk mengatakan 'Istirahatlah dari cinta yang salah'.\n *Bye Instagram:* @itz.dapaa",
  "Jomblo adalah anak muda yang mendahulukan pengembangan pribadinya untuk cinta yang lebih berkelas nantinya.\n *Bye Instagram:* @itz.dapaa",
  "Aku bukan mencari seseorang yang sempurna, tapi aku mencari orang yang menjadi sempurna berkat kelebihanku.\n *Bye Instagram:* @itz.dapaa",
  "Pacar orang adalah jodoh kita yang tertunda.\n *Bye Instagram:* @itz.dapaa",
  "Jomblo pasti berlalu. Semua ada saatnya, saat semua kesendirian menjadi sebuah kebersamaan dengannya kekasih halal. Bersabarlah.\n *Bye Instagram:* @itz.dapaa",
  "Romeo rela mati untuk juliet, Jack mati karena menyelamatkan Rose. Intinya, kalau tetap mau hidup, jadilah single.\n *Bye Instagram:* @itz.dapaa",
  "Aku mencari orang bukan dari kelebihannya tapi aku mencari orang dari ketulusan hatinya.\n *Bye Instagram:* @itz.dapaa",
  "Jodoh bukan sendal jepit, yang kerap tertukar. Jadi teruslah berada dalam perjuangan yang semestinya.\n *Bye Instagram:* @itz.dapaa",
  "Kalau kamu jadi senar gitar, aku nggak mau jadi gitarisnya. Karena aku nggak mau mutusin kamu.\n *Bye Instagram:* @itz.dapaa",
  "Bila mencintaimu adalah ilusi, maka izinkan aku berimajinasi selamanya.\n *Bye Instagram:* @itz.dapaa",
  "Sayang... Tugas aku hanya mencintaimu, bukan melawan takdir.\n *Bye Instagram:* @itz.dapaa",
  "Saat aku sedang bersamamu rasanya 1 jam hanya 1 detik, tetapi jika aku jauh darimu rasanya 1 hari menjadi 1 tahun.\n *Bye Instagram:* @itz.dapaa",
  "Kolak pisang tahu sumedang, walau jarak membentang cintaku takkan pernah hilang.\n *Bye Instagram:* @itz.dapaa",
  "Aku ingin menjadi satu-satunya, bukan salah satunya.\n *Bye Instagram:* @itz.dapaa",
  "Aku tidak bisa berjanji untuk menjadi yang baik. Tapi aku berjanji akan selalu mendampingi kamu.\n *Bye Instagram:* @itz.dapaa",
  "Kalau aku jadi wakil rakyat aku pasti gagal, gimana mau mikirin rakyat kalau yang selalu ada dipikiran aku hanyalah dirimu.\n *Bye Instagram:* @itz.dapaa",
  "Lihat kebunku, penuh dengan bunga. Lihat matamu, hatiku berbunga-bunga.\n *Bye Instagram:* @itz.dapaa",
  "Berjanjilah untuk terus bersamaku sekarang, esok, dan selamanya.\n *Bye Instagram:* @itz.dapaa",
  "Rindu tidak hanya muncul karena jarak yang terpisah. Tapi juga karena keinginan yang tidak terwujud.\n *Bye Instagram:* @itz.dapaa",
  "Kamu tidak akan pernah jauh dariku, kemanapun aku pergi kamu selalu ada, karena kamu selalu di hatiku, yang jauh hanya raga kita bukan hati kita.\n *Bye Instagram:* @itz.dapaa",
  "Aku tahu dalam setiap tatapanku, kita terhalang oleh jarak dan waktu. Tapi aku yakin kalau nanti kita pasti bisa bersatu.\n *Bye Instagram:* @itz.dapaa",
  "Merindukanmu tanpa pernah bertemu sama halnya dengan menciptakan lagu yang tak pernah ternyayikan.\n *Bye Instagram:* @itz.dapaa",
  "Ada kalanya jarak selalu menjadi penghalang antara aku sama kamu, namun tetap saja di hatiku kita selalu dekat.\n *Bye Instagram:* @itz.dapaa",
  "Jika hati ini tak mampu membendung segala kerinduan, apa daya tak ada yang bisa aku lakukan selain mendoakanmu.\n *Bye Instagram:* @itz.dapaa",
  "Mungkin di saat ini aku hanya bisa menahan kerinduan ini. Sampai tiba saatnya nanti aku bisa bertemu dan melepaskan kerinduan ini bersamamu.\n *Bye Instagram:* @itz.dapaa",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu.\n *Bye Instagram:* @itz.dapaa",
  "Dalam dinginnya malam, tak kuingat lagi; Berapa sering aku memikirkanmu juga merindukanmu.\n *Bye Instagram:* @itz.dapaa",
  "Merindukanmu itu seperti hujan yang datang tiba-tiba dan bertahan lama. Dan bahkan setelah hujan reda, rinduku masih terasa.\n *Bye Instagram:* @itz.dapaa",
  "Sejak mengenalmu bawaannya aku pengen belajar terus, belajar menjadi yang terbaik buat kamu.\n *Bye Instagram:* @itz.dapaa",
  "Tahu gak perbedaan pensi sama wajah kamu? Kalau pensil tulisannya bisa dihapus, tapi kalau wajah kamu gak akan ada yang bisa hapus dari pikiran aku.\n *Bye Instagram:* @itz.dapaa",
  "Bukan Ujian Nasional besok yang harus aku khawatirkan, tapi ujian hidup yang aku lalui setelah kamu meninggalkanku.\n *Bye Instagram:* @itz.dapaa",
  "Satu hal kebahagiaan di sekolah yang terus membuatku semangat adalah bisa melihat senyumanmu setiap hari.\n *Bye Instagram:* @itz.dapaa",
  "Kamu tahu gak perbedaanya kalau ke sekolah sama ke rumah kamu? Kalo ke sekolah pasti yang di bawa itu buku dan pulpen, tapi kalo ke rumah kamu, aku cukup membawa hati dan cinta.\n *Bye Instagram:* @itz.dapaa",
  "Aku gak sedih kok kalo besok hari senin, aku sedihnya kalau gak ketemu kamu.\n *Bye Instagram:* @itz.dapaa",
  "Momen cintaku tegak lurus dengan momen cintamu. Menjadikan cinta kita sebagai titik ekuilibrium yang sempurna.\n *Bye Instagram:* @itz.dapaa",
  "Aku rela ikut lomba lari keliling dunia, asalkan engkai yang menjadi garis finishnya.\n *Bye Instagram:* @itz.dapaa",
  "PR-ku adalah merindukanmu. Lebih kuat dari Matematika, lebih luas dari Fisika, lebih kerasa dari Biologi.\n *Bye Instagram:* @itz.dapaa",
  "Cintaku kepadamu itu bagaikan metabolisme, yang gak akan berhenti sampai mati.\n *Bye Instagram:* @itz.dapaa",
  "Kalau jelangkungnya kaya kamu, dateng aku jemput, pulang aku anter deh.\n *Bye Instagram:* @itz.dapaa",
  "Makan apapun aku suka asal sama kamu, termasuk makan ati.\n *Bye Instagram:* @itz.dapaa",
  "Cinta itu kaya hukuman mati. Kalau nggak ditembak, ya digantung.\n *Bye Instagram:* @itz.dapaa",
  "Mencintaimu itu kayak narkoba: sekali coba jadi candu, gak dicoba bikin penasaran, ditinggalin bikin sakaw.\n *Bye Instagram:* @itz.dapaa",
  "Gue paling suka ngemil karena ngemil itu enak. Apalagi ngemilikin kamu sepenuhnya...\n *Bye Instagram:* @itz.dapaa",
  "Dunia ini cuma milik kita berdua. Yang lainnya cuma ngontrak.\n *Bye Instagram:* @itz.dapaa",
  "Bagi aku, semua hari itu adalah hari Selasa. Selasa di Surga bila dekat denganmu...\n *Bye Instagram:* @itz.dapaa",
  "Bagaimana kalau kita berdua jadi komplotan penjahat? Aku curi hatimu dan kamu curi hatiku.\n *Bye Instagram:* @itz.dapaa",
  "Kamu itu seperti kopi yang aku seruput pagi ini. Pahit, tapi bikin nagih.\n *Bye Instagram:* @itz.dapaa",
  "Aku sering cemburu sama lipstikmu. Dia bisa nyium kamu tiap hari, dari pagi sampai malam.\n *Bye Instagram:* @itz.dapaa",
  "Hanya mendengar namamu saja sudah bisa membuatku tersenyum seperti orang bodoh.\n *Bye Instagram:* @itz.dapaa",
  "Aku tau teman wanitamu bukan hanya satu, dan menyukaimu pun bukan hanya aku.\n *Bye Instagram:* @itz.dapaa",
  "Semenjak aku berhenti berharap pada dirimu, aku jadi tidak semangat dalam segala hal..\n *Bye Instagram:* @itz.dapaa",
  "Denganmu, jatuh cinta adalah patah hati paling sengaja.\n *Bye Instagram:* @itz.dapaa",
  "Sangat sulit merasakan kebahagiaan hidup tanpa kehadiran kamu disisiku.\n *Bye Instagram:* @itz.dapaa",
  "Melalui rasa rindu yang bergejolak dalam hati, di situ terkadang aku sangat membutuhkan dekap peluk kasih sayangmu.\n *Bye Instagram:* @itz.dapaa",
  "Sendainya kamu tahu, sampai saat ini aku masih mencintaimu.\n *Bye Instagram:* @itz.dapaa",
  "Terkadang aku iri sama layangan..talinya putus saja masih dikejar kejar dan gak rela direbut orang lain...\n *Bye Instagram:* @itz.dapaa",
  "Aku tidak tahu apa itu cinta, sampai akhirnya aku bertemu denganmu. Tapi, saat itu juga aku tahu rasanya patah hati.\n *Bye Instagram:* @itz.dapaa",
  "Mengejar itu capek, tapi lebih capek lagi menunggu\nMenunggu kamu menyadari keberadaanku...\n *Bye Instagram:* @itz.dapaa",
  "Jangan berhenti mencinta hanya karena pernah terluka. Karena tak ada pelangi tanpa hujan, tak ada cinta sejati tanpa tangisan.\n *Bye Instagram:* @itz.dapaa",
  "Aku punya sejuta alasan unutk melupakanmu, tapi tak ada yang bisa memaksaku untuk berhenti mencintaimu.\n *Bye Instagram:* @itz.dapaa",
  "Terkadang seseorang terasa sangat bodoh hanya untuk mencintai seseorang.\n *Bye Instagram:* @itz.dapaa",
  "Kamu adalah patah hati terbaik yang gak pernah aku sesali.\n *Bye Instagram:* @itz.dapaa",
  "Bukannya tak pantas ditunggu, hanya saja sering memberi harapan palsu.\n *Bye Instagram:* @itz.dapaa",
  "Sebagian diriku merasa sakit, Mengingat dirinya yang sangat dekat, tapi tak tersentuh.\n *Bye Instagram:* @itz.dapaa",
  "Hal yang terbaik dalam mencintai seseorang adalah dengan diam-diam mendo akannya.\n *Bye Instagram:* @itz.dapaa",
  "Kuharap aku bisa menghilangkan perasaan ini secepat aku kehilanganmu.\n *Bye Instagram:* @itz.dapaa",
  "Demi cinta kita menipu diri sendiri. Berusaha kuat nyatanya jatuh secara tak terhormat.\n *Bye Instagram:* @itz.dapaa",
  "Anggaplah aku rumahmu, jika kamu pergi kamu mengerti kemana arah pulang. Menetaplah bila kamu mau dan pergilah jika kamu bosan...\n *Bye Instagram:* @itz.dapaa",
  "Aku bingung, apakah aku harus kecewa atu tidak? Jika aku kecewa, emang siapa diriku baginya?\n\nKalau aku tidak kecewa, tapi aku menunggu ucapannya.\n *Bye Instagram:* @itz.dapaa",
  "Rinduku seperti ranting yang tetap berdiri.Meski tak satupun lagi dedaunan yang menemani, sampai akhirnya mengering, patah, dan mati.\n *Bye Instagram:* @itz.dapaa",
  "Kurasa kita sekarang hanya dua orang asing yang memiliki kenangan yang sama.\n *Bye Instagram:* @itz.dapaa",
  "Buatlah aku bisa membencimu walau hanya beberapa menit, agar tidak terlalu berat untuk melupakanmu.\n *Bye Instagram:* @itz.dapaa",
  "Aku mencintaimu dengan segenap hatiku, tapi kau malah membagi perasaanmu dengan orang lain.\n *Bye Instagram:* @itz.dapaa",
  "Mencintaimu mungkin menghancurkanku, tapi entah bagaimana meninggalkanmu tidak memperbaikiku.\n *Bye Instagram:* @itz.dapaa",
  "Kamu adalah yang utama dan pertama dalam hidupku. Tapi, aku adalah yang kedua bagimu.\n *Bye Instagram:* @itz.dapaa",
  "Jika kita hanya bisa dipertemukan dalam mimpi, aku ingin tidur selamanya.\n *Bye Instagram:* @itz.dapaa",
  "Melihatmu bahagia adalah kebahagiaanku, walaupun bahagiamu tanpa bersamaku.\n *Bye Instagram:* @itz.dapaa",
  "Aku terkadang iri dengan sebuah benda. Tidak memiliki rasa namun selalu dibutuhkan. Berbeda dengan aku yang memiliki rasa, namun ditinggalkan dan diabaikan...\n *Bye Instagram:* @itz.dapaa",
  "Bagaimana mungkin aku berpindah jika hanya padamu hatiku bersinggah?\n *Bye Instagram:* @itz.dapaa",
  "Kenangan tentangmu sudah seperti rumah bagiku. Sehingga setiap kali pikiranku melayang, pasti ujung-ujungnya akan selalu kembali kepadamu.\n *Bye Instagram:* @itz.dapaa",
  "Kenapa tisue bermanfaat? Karena cinta tak pernah kemarau. - Sujiwo Tejo\n *Bye Instagram:* @itz.dapaa",
  "Kalau mencintaimu adalah kesalahan, yasudah, biar aku salah terus saja.\n *Bye Instagram:* @itz.dapaa",
  "Sejak kenal kamu, aku jadi pengen belajar terus deh. Belajar jadi yang terbaik buat kamu.\n *Bye Instagram:* @itz.dapaa",
  "Ada yang bertingkah bodoh hanya untuk melihatmu tersenyum. Dan dia merasa bahagia akan hal itu.\n *Bye Instagram:* @itz.dapaa",
  "Aku bukan orang baik, tapi akan belajar jadi yang terbaik untuk kamu.\n *Bye Instagram:* @itz.dapaa",
  "Kita tidak mati, tapi lukanya yang membuat kita tidak bisa berjalan seperti dulu lagi.\n *Bye Instagram:* @itz.dapaa",
  "keberadaanmu bagaikan secangkir kopi yang aku butuhkan setiap pagi, yang dapat mendorongku untuk tetap bersemangat menjalani hari.\n *Bye Instagram:* @itz.dapaa",
  "Aku mau banget ngasih dunia ke kamu. Tapi karena itu nggak mungkin, maka aku akan kasih hal yang paling penting dalam hidupku, yaitu duniaku.\n *Bye Instagram:* @itz.dapaa",
  "Mending sing humoris tapi manis, ketimbang sok romantis tapi akhire tragis.\n *Bye Instagram:* @itz.dapaa",
  "Ben akhire ora kecewa, dewe kudu ngerti kapan waktune berharap lan kapan kudu mandeg.\n *Bye Instagram:* @itz.dapaa",
  "Aku ki wong Jowo seng ora ngerti artine 'I Love U'. Tapi aku ngertine mek 'Aku tresno awakmu'.\n *Bye Instagram:* @itz.dapaa",
  "Ora perlu ayu lan sugihmu, aku cukup mok setiani wes seneng ra karuan.\n *Bye Instagram:* @itz.dapaa",
  "Cintaku nang awakmu iku koyok kamera, fokus nang awakmu tok liyane mah ngeblur.\n *Bye Instagram:* @itz.dapaa",
  "Saben dino kegowo ngimpi tapi ora biso nduweni.\n *Bye Instagram:* @itz.dapaa",
  "Ora ketemu koe 30 dino rasane koyo sewulan.\n *Bye Instagram:* @itz.dapaa",
  "Aku tanpamu bagaikan sego kucing ilang karete. Ambyar.\n *Bye Instagram:* @itz.dapaa",
  "Pengenku, Aku iso muter wektu. Supoyo aku iso nemokne kowe lewih gasik. Ben Lewih dowo wektuku kanggo urip bareng sliramu.\n *Bye Instagram:* @itz.dapaa",
  "Aku ora pernah ngerti opo kui tresno, kajaba sak bare ketemu karo sliramu.\n *Bye Instagram:* @itz.dapaa",
  "Cinta aa ka neng moal leungit-leungit sanajan aa geus kawin deui.\n *Bye Instagram:* @itz.dapaa",
  "Kasabaran kaula aya batasna, tapi cinta kaula ka anjeun henteu aya se epna.\n *Bye Instagram:* @itz.dapaa",
  "Kanyaah akang moal luntur najan make Bayclean.\n *Bye Instagram:* @itz.dapaa",
  "Kenangan endah keur babarengan jeung anjeun ek tuluy diinget-inget nepi ka poho.\n *Bye Instagram:* @itz.dapaa",
  "Kuring moal bakal tiasa hirup sorangan, butuh bantosan jalmi sejen.\n *Bye Instagram:* @itz.dapaa",
  "Nyaahna aa ka neg teh jiga tukang bank keur nagih hutang (hayoh mumuntil).\n *Bye Instagram:* @itz.dapaa",
  "Kasabaran urang aya batasna, tapi cinta urang ka maneh moal aya beakna.\n *Bye Instagram:* @itz.dapaa",
  "Hayang rasana kuring ngarangkai kabeh kata cinta anu aya di dunya ieu, terus bade ku kuring kumpulkeun, supaya anjeun nyaho gede pisan rasa cinta kuring ka anjeun.\n *Bye Instagram:* @itz.dapaa",
  "Tenang wae neng, ari cinta Akang mah sapertos tembang krispatih; Tak lekang oleh waktu.\n *Bye Instagram:* @itz.dapaa",
  "Abdi sanes jalmi nu sampurna pikeun anjeun, sareng sanes oge nu paling alus kanggo anjeun. Tapi nu pasti, abdi jalmi hiji-hijina nu terus emut ka anjeun.\n *Bye Instagram:* @itz.dapaa",
  "Cukup jaringan aja yang hilang, kamu jangan.\n *Bye Instagram:* @itz.dapaa",
  "Sering sih dibikin makan ati. Tapi menyadari kamu masih di sini bikin bahagia lagi.\n *Bye Instagram:* @itz.dapaa",
  "Musuhku adalah mereka yang ingin memilikimu juga.\n *Bye Instagram:* @itz.dapaa",
  "Banyak yang selalu ada, tapi kalo cuma kamu yang aku mau, gimana?\n *Bye Instagram:* @itz.dapaa",
  "Jam tidurku hancur dirusak rindu.\n *Bye Instagram:* @itz.dapaa",
  "Cukup China aja yang jauh, cinta kita jangan.\n *Bye Instagram:* @itz.dapaa",
  "Yang penting itu kebahagiaan kamu, aku sih gak penting..\n *Bye Instagram:* @itz.dapaa",
  "Cuma satu keinginanku, dicintai olehmu..\n *Bye Instagram:* @itz.dapaa",
  "Aku tanpamu bagaikan ambulans tanpa wiuw wiuw wiuw.\n *Bye Instagram:* @itz.dapaa",
  "Cukup antartika aja yang jauh. Antarkita jangan.\n *Bye Instagram:* @itz.dapaa",
]
